services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    command: sh -c "npm run seed && npm start"
    networks:
      - mindbloom-network

networks:
  mindbloom-network:
    driver: bridge

volumes: {}
