CREATE TABLE IF NOT EXISTS teachers (
    TID VARCHAR(50) PRIMARY KEY,
    TNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BIO TEXT,
    PASS VARCHAR(255),
    SPECIAL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS courses (
    CID VARCHAR(50) PRIMARY KEY,
    TITLE VARCHAR(50),
    DESCRIP TEXT,
    VIDEO INTEGER,
    TID VARCHAR(50) REFERENCES teachers(TID),
    IMGLINK VARCHAR(400),
    VIDLINK VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS users (
    USERID VARCHAR(50) PRIMARY KEY,
    UNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    PSWD VARCHAR(255),
    IMG VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS enrollments (
    EID VARCHAR(50) PRIMARY KEY,
    USERID VARCHAR(50) REFERENCES users(USERID),
    CID VARCHAR(50) REFERENCES courses(CID)
);

CREATE TABLE IF NOT EXISTS admins (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

