CREATE TABLE IF NOT EXISTS TEACHER (
    TID VARCHAR(50) PRIMARY KEY,
    TNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BIO VARCHAR(250),
    PASS VARCHAR(20),
    SPECIAL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS COURSE (
    CID VARCHAR(50) PRIMARY KEY,
    TITLE VARCHAR(50),
    DESCRIP VARCHAR(250),
    VIDEO INTEGER,
    TID VARCHAR(50) REFERENCES TEACHER(TID),
    IMGLINK VARCHAR(400),
    VIDLINK VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS "USER" (
    USERID VARCHAR(50) PRIMARY KEY,
    UNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    PSWD VARCHAR(20),
    IMG VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS ENROLLMENT (
    EID VARCHAR(50) PRIMARY KEY,
    USERID VARCHAR(50) REFERENCES "USER"(USERID),
    CID VARCHAR(50) REFERENCES COURSE(CID)
);

CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADMINS (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
