CREATE DATABASE IF NOT EXISTS project;
USE project;

CREATE TABLE IF NOT EXISTS TEACHER(
    TID VARCHAR(50) PRIMARY KEY,
    TNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    BIO VARCHAR(250),
    PASS VARCHAR(20),
    SPECIAL VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS COURSE(
    CID VARCHAR(50) PRIMARY KEY,
    TITLE VARCHAR(50),
    DESCRIP VARCHAR(250),
    VIDEO INT,
    TID VARCHAR(50),
    IMGLINK VARCHAR(400),
    VIDLINK VARCHAR(400),
    FOREIGN KEY (TID) REFERENCES TEACHER(TID)
);

CREATE TABLE IF NOT EXISTS USER(
    USERID VARCHAR(50) PRIMARY KEY,
    UNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50),
    PSWD VARCHAR(20),
    IMG VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS ENROLLMENT(
    EID VARCHAR(50) PRIMARY KEY,
    USERID VARCHAR(50),
    CID VARCHAR(50),
    FOREIGN KEY (CID) REFERENCES COURSE(CID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);


CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADMINS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);
